name: Manual Run it
on:
 workflow_dispatch:
   inputs:
     logLevel:
       description: 'Log level'
       required: true
       default: 'warning' 
       type: choice
       options:
       - info
       - warning
       - debug 
     tags:
       description: 'Test scenario tags'
       required: false 
       type: boolean
     environment:
       description: 'Environment to run tests against'
       type: environment
       required: true 

jobs:
 print-tag:
   runs-on: ubuntu-latest

   steps:
     - name: Print the input tag to STDOUT
     - run: echo The tag is ${{ github.event.inputs.tag }}
